// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
// import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

// await Firebase.initializeApp(
//     options: DefaultFirebaseOptions.currentPlatform,
// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM7aAvywIcBNAhoZ0-nvaoVcKXots9g_w',
    appId: '1:631496190459:web:7af7bd4f786aa4fd17835e',
    messagingSenderId: '631496190459',
    projectId: 'healthsync-c0879',
    authDomain: 'healthsync-c0879.firebaseapp.com',
    storageBucket: 'healthsync-c0879.firebasestorage.app',
    measurementId: 'G-GZHK6042WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeEe0ovLnFouiyjC-KFTCN5FOU5gs5Qcw',
    appId: '1:631496190459:android:31b396019b6d4f9c17835e',
    messagingSenderId: '631496190459',
    projectId: 'healthsync-c0879',
    storageBucket: 'healthsync-c0879.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdyDKsvv11VwwqHnBYyi9NgjMmcQFmmLs',
    appId: '1:631496190459:ios:5621bb520c92ae0417835e',
    messagingSenderId: '631496190459',
    projectId: 'healthsync-c0879',
    storageBucket: 'healthsync-c0879.firebasestorage.app',
    iosBundleId: 'com.example.healthsyncDemoV0100',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdyDKsvv11VwwqHnBYyi9NgjMmcQFmmLs',
    appId: '1:631496190459:ios:5621bb520c92ae0417835e',
    messagingSenderId: '631496190459',
    projectId: 'healthsync-c0879',
    storageBucket: 'healthsync-c0879.firebasestorage.app',
    iosBundleId: 'com.example.healthsyncDemoV0100',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM7aAvywIcBNAhoZ0-nvaoVcKXots9g_w',
    appId: '1:631496190459:web:262fa7a0f553f5ad17835e',
    messagingSenderId: '631496190459',
    projectId: 'healthsync-c0879',
    authDomain: 'healthsync-c0879.firebaseapp.com',
    storageBucket: 'healthsync-c0879.firebasestorage.app',
    measurementId: 'G-W68HGZLK8F',
  );
}
